apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# See ../../README.md. `env` is off-limits to patch.yaml.
namespace: kamis

namePrefix: purchase-

resources:
- ../../../base

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app: purchase

images:
- name: us-central1-docker.pkg.dev/ops-lab-506804/lab-images/kamis
  newName: us-central1-docker.pkg.dev/ops-lab-506804/lab-images/kamis-purchase
  newTag: a65c4e1

patches:
- path: patch.yaml
