# base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - vm-single.yaml
  - service.yaml
  - rbac.yaml
  - scrape-config.yaml
  - vmagent.yaml
  - ksm.yaml
  - ksm-rbac.yaml