apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: dev
images:
- name: us-central1-docker.pkg.dev/ops-lab-506804/lab-images/lab-app
  newName: us-central1-docker.pkg.dev/ops-lab-506804/lab-images/lab-app
  newTag: 387c32e
